name: CD - Build Frontend

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - Frontend/**

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Frontend
    steps:
      - name: Build Started - Message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”
            âš›ï¸ *FRONTEND DEPLOYMENT*
            â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”

            â–¶ï¸ *Status*: STARTED

            ğŸ“¦ *Repository*: `${{ github.repository }}`
            ğŸŒ¿ *Branch*: `${{ github.ref_name }}`
            ğŸ‘¤ *Triggered by*: `${{ github.actor }}`
            ğŸ”— [View Commit](https://github.com/${{ github.repository }}/commit/${{ github.sha }})

            â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"
          cache-dependency-path: ./Frontend/package-lock.json

      - name: Setup is completed - Message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            âš™ï¸ *SETUP COMPLETED*

            ğŸ”§ *Phase*: Node.js Environment
            ğŸ‘¤ *Actor*: `${{ github.actor }}`
            ğŸ“ *Commit*: `${{ github.event.commits[0].message }}`
            ğŸ”— [View Commit](https://github.com/${{ github.repository }}/commit/${{ github.sha }})

      - name: login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Set build number
        id: build-number
        run: echo "BUILD_NUMBER=$(date +'%d.%m.%Y.%H.%M.%S')" >> $GITHUB_OUTPUT

      - name: build number - Message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ğŸ”¢ *BUILD VERSION*

            ğŸ§± *Version*: `${{ steps.build-number.outputs.BUILD_NUMBER }}`
            ğŸ‘¤ *Author*: `${{ github.actor }}`
            ğŸ”— [View Commit](https://github.com/${{ github.repository }}/commit/${{ github.sha }})

      - name: Build and Push Docker Image
        run: docker build . --push -t ${{ secrets.DOCKERHUB_USERNAME }}/mailmine-frontend:${{steps.build-number.outputs.BUILD_NUMBER}} -t ${{ secrets.DOCKERHUB_USERNAME }}/mailmine-frontend:latest

      - name: action is completed! - Message
        if: success()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            â•”â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•—
            â•‘  âœ… DEPLOYMENT SUCCESS  â•‘
            â•šâ•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•

            ğŸ‰ *Frontend Deployed Successfully*

            ğŸ‘¤ *Deployed by*: `${{ github.actor }}`
            ğŸ”– *Build*: `${{ steps.build-number.outputs.BUILD_NUMBER }}`
            ğŸ“¦ *Repository*: `${{ github.repository }}`
            ğŸ”— [Final Commit](https://github.com/${{ github.repository }}/commit/${{ github.sha }})

            â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”

      - name: Send Telegram message on failure - Message
        if: failure()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            â•”â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•—
            â•‘  âŒ DEPLOYMENT FAILED  â•‘
            â•šâ•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•

            ğŸš¨ *Frontend Deployment Failed*

            ğŸ‘¤ *Triggered by*: `${{ github.actor }}`
            ğŸ“ *Commit*: `${{ github.event.commits[0].message }}`
            ğŸ“¦ *Repository*: `${{ github.repository }}`
            ğŸ”— [View Commit](https://github.com/${{ github.repository }}/commit/${{ github.sha}})

            ğŸ›  *Action Required*: [Check Logs](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})

            â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”
